### ISSUE TITLE
[EventProducer] has been invalidated and can no longer produce events.

### ISSUE THREAD

**Issue by bubunyo** [AndroidKnife/RxBus#18]
When an activity exist for too long then this happens producers get invalidated. I posted it as a question on stackover but i have received any answers yet. Any idea what is goin on here?

``` java
Fatal Exception: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:112)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by rx.exceptions.OnErrorNotImplementedException: [EventProducer public xyz.chanl.radio.events.Events$StageStation xyz.chanl.radio.fragments.StationsListFragment.stageStation()] has been invalidated and can no longer produce events.
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
       at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
       at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
       at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
       at rx.Observable.unsafeSubscribe(Observable.java:8673)
       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by java.lang.IllegalStateException: [EventProducer public xyz.chanl.radio.events.Events$StageStation xyz.chanl.radio.fragments.StationsListFragment.stageStation()] has been invalidated and can no longer produce events.
       at com.hwangjr.rxbus.entity.ProducerEvent.produceEvent(ProducerEvent.java:98)
       at com.hwangjr.rxbus.entity.ProducerEvent.access$000(ProducerEvent.java:17)
       at com.hwangjr.rxbus.entity.ProducerEvent$1.call(ProducerEvent.java:80)
       at com.hwangjr.rxbus.entity.ProducerEvent$1.call(ProducerEvent.java:76)
       at rx.Observable.unsafeSubscribe(Observable.java:8666)
       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
       at rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:107)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by hwangjr** [comment]
This means you have unregister the producer, maybe you can post more details about the error, like code etc...

**Comment by hwangjr** [comment]
you can try register the RxBus on `onCreate`, and unregister this on `onDestroy`. it seems that you want to call an invalidated producer.

**Comment by orignMaster** [comment]
am `registering/unregistering` in `onStop/onStart`. The android documentations says the `onDestroy` is not guaranteed to be called.

**Comment by hwangjr** [comment]
you mean the document about [Activity | Android Developers](https://developer.android.com/reference/android/app/Activity.html) ?

**Comment by orignMaster** [comment]
Yah, thats right

**Comment by hwangjr** [comment]
Sorry, i can't capture this issue, can you provide an Operation Guide or some code segment for me ?

**Comment by bubunyo** [comment]
i have been looking at the issue more and i have a theory.

Naturally when you create an activity with the event bus, producers are fired. When the activity is finished  , some how the producer gets called, and since there is not activity attached, the producer is invalidated.

Is there a way to check if and activity is alive before producers are called?

**Comment by hwangjr** [comment]
when the activity is finished, you should call `RxBus.get().unregister()` to unregister the subscriber/producer.

**Comment by hwangjr** [comment]
If you have fix the problem, you can close the issue. Or maybe you can create a repo for your code, I will create a PR for it.

**Comment by bubunyo** [comment]
So, I investigated this problem and i realized it comes from producing the same event from multiple places. So when the producer is registered with a particular event it invalidates the second one. I don't know if this design is by choice, but i think the mechanism for registering producers should be in such a way as to allow multiple producers to emit events of the same type.

**Comment by hwangjr** [comment]
multiple producers is not the topic about this issue, maybe you can open a new issue to talk about this?
you can reopen this issue if you still have some questions and provide more codes, like a repo, so i can fork it to figure out what's going on.

**Comment by bubunyo** [comment]
but multiple producers was the cause of this issue. I will create a repo and try to replicate the issue

**Comment by blakecarrier** [comment]
Has this issue been addressed? I am running into the same issue

**Comment by bubunyo** [comment]
If you are producing the same event from 2 different classes, that might be your source

**Comment by blakecarrier** [comment]
It looks like its due to rotation we unregister in onPause and Register in onResume. When you rotate, while the screen is still loading, it crashes and presents this error.
