### ISSUE TITLE
调用register时闪退。release版本。混淆已配置

### ISSUE THREAD

**Issue by ArtisanM** [AndroidKnife/RxBus#28]
```
java.lang.NoSuchFieldError
                                                                     at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:688)
                                                                     at libcore.reflect.AnnotationAccess.getDefaultValue(AnnotationAccess.java:361)
                                                                     at java.lang.reflect.Method.getDefaultValue(Method.java:327)
                                                                     at libcore.reflect.AnnotationFactory.getElementsDescription(AnnotationFactory.java:75)
                                                                     at libcore.reflect.AnnotationFactory.<init>(AnnotationFactory.java:112)
                                                                     at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:94)
                                                                     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:666)
                                                                     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
                                                                     at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
                                                                     at java.lang.reflect.Method.getAnnotation(Method.java:301)
                                                                     at com.hwangjr.rxbus.b.a.a(SourceFile:81)
                                                                     at com.hwangjr.rxbus.b.a.a(SourceFile:40)
                                                                     at com.hwangjr.rxbus.b.a.a(SourceFile:157)
                                                                     at com.hwangjr.rxbus.b.b$1.a(SourceFile:23)
                                                                     at com.hwangjr.rxbus.a.a(SourceFile:179)
                                                                     at com.yueke.astraea.MainActivity.onCreate(SourceFile:94)
                                                                     at android.app.Activity.performCreate(Activity.java:6107)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2373)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
                                                                     at android.app.ActivityThread.access$900(ActivityThread.java:164)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:150)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5408)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
                                                                  Caused by: java.lang.NoSuchFieldException: MAIN_THREAD
                                                                     at java.lang.Class.getDeclaredField(Class.java:890)
                                                                     at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:685)
                                                                     at libcore.reflect.AnnotationAccess.getDefaultValue(AnnotationAccess.java:361) 
                                                                     at java.lang.reflect.Method.getDefaultValue(Method.java:327) 
                                                                     at libcore.reflect.AnnotationFactory.getElementsDescription(AnnotationFactory.java:75) 
                                                                     at libcore.reflect.AnnotationFactory.<init>(AnnotationFactory.java:112) 
                                                                     at libcore.reflect.AnnotationFactory.createAnnotation(AnnotationFactory.java:94) 
                                                                     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:666) 
                                                                     at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641) 
                                                                     at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170) 
                                                                     at java.lang.reflect.Method.getAnnotation(Method.java:301) 
                                                                     at com.hwangjr.rxbus.b.a.a(SourceFile:81) 
                                                                     at com.hwangjr.rxbus.b.a.a(SourceFile:40) 
                                                                     at com.hwangjr.rxbus.b.a.a(SourceFile:157) 
                                                                     at com.hwangjr.rxbus.b.b$1.a(SourceFile:23) 
                                                                     at com.hwangjr.rxbus.a.a(SourceFile:179) 
                                                                     at com.yueke.astraea.MainActivity.onCreate(SourceFile:94) 
                                                                     at android.app.Activity.performCreate(Activity.java:6107) 
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2373) 
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493) 
                                                                     at android.app.ActivityThread.access$900(ActivityThread.java:164) 
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377) 
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                     at android.os.Looper.loop(Looper.java:150) 
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5408) 
                                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964) 
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759) 
```

**Comment by hwangjr** [comment]
#7 & #20    checkout this.
