### ISSUE TITLE
要怎么配置混淆文件

### ISSUE THREAD

**Issue by kebbs** [AndroidKnife/RxBus#7]
如果没有混淆则app正常,但一旦混淆了,及出现这个错误,我已经配置了不混淆
###rxbus
-dontwarn com.hwangjr.rxbus.**
-keep class com.hwangjr.rxbus.** { *;}

java.lang.InternalError
                                                            at d.d.d.b.y.a(UnsafeAccess.java:103)
                                                            at d.d.d.b.x.<clinit>(SpscArrayQueue.java:39)
                                                            at d.d.a.r.<init>(OperatorObserveOn.java:94)
                                                            at d.d.a.q.a(OperatorObserveOn.java:64)
                                                            at d.d.a.q.call(OperatorObserveOn.java:44)
                                                            at d.b.a(Observable.java:158)
                                                            at d.b.call(Observable.java:154)
                                                            at d.a.a(Observable.java:8191)
                                                            at d.a.b(Observable.java:8158)
                                                            at d.a.a(Observable.java:7914)
                                                            at com.hwangjr.rxbus.entity.SubscriberEvent.initObservable(SubscriberEvent.java:73)
                                                            at com.hwangjr.rxbus.entity.SubscriberEvent.<init>(SubscriberEvent.java:63)
                                                            at com.hwangjr.rxbus.finder.AnnotatedFinder.findAllSubscribers(AnnotatedFinder.java:185)
                                                            at com.hwangjr.rxbus.finder.Finder$1.findAllSubscribers(Finder.java:28)
                                                            at com.hwangjr.rxbus.Bus.register(Bus.java:198)

**Comment by hwangjr** [comment]
[proguard-rules.pro](https://github.com/AndroidKnife/RxBus/blob/master/rxbus%2Fproguard-rules.pro)

Check out this file~

**Comment by huweigoodboy** [comment]
我按照上面的配置　　报下面这个错误

 java.lang.NoSuchFieldError
                                                       at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:688)
                                                       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663)
                                                       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641)
                                                       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170)
                                                       at java.lang.reflect.Method.getAnnotation(Method.java:301)
                                                       at com.hwangjr.rxbus.finder.AnnotatedFinder.a(Unknown Source)
                                                       at com.hwangjr.rxbus.finder.AnnotatedFinder.a(Unknown Source)
                                                       at com.hwangjr.rxbus.finder.AnnotatedFinder.a(Unknown Source)
                                                       at com.hwangjr.rxbus.finder.Finder$1.findAllProducers(Unknown Source)
                                                       at com.hwangjr.rxbus.Bus.register(Unknown Source)
                                                       at cn.youcaitv.live.e.a.a.onCreate(Unknown Source)
                                                       at cn.youcaitv.live.usercenter.PreLoginActivity.onCreate(Unknown Source)
                                                       at android.app.Activity.performCreate(Activity.java:6100)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2401)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
                                                       at android.app.ActivityThread.access$1200(ActivityThread.java:163)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5595)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                    Caused by: java.lang.NoSuchFieldException: MAIN_THREAD
                                                       at java.lang.Class.getDeclaredField(Class.java:890)
                                                       at libcore.reflect.AnnotationAccess.decodeValue(AnnotationAccess.java:685)
                                                       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:663) 
                                                       at libcore.reflect.AnnotationAccess.toAnnotationInstance(AnnotationAccess.java:641) 
                                                       at libcore.reflect.AnnotationAccess.getDeclaredAnnotation(AnnotationAccess.java:170) 
                                                       at java.lang.reflect.Method.getAnnotation(Method.java:301) 
                                                       at com.hwangjr.rxbus.finder.AnnotatedFinder.a(Unknown Source) 
                                                       at com.hwangjr.rxbus.finder.AnnotatedFinder.a(Unknown Source) 
                                                       at com.hwangjr.rxbus.finder.AnnotatedFinder.a(Unknown Source) 
                                                       at com.hwangjr.rxbus.finder.Finder$1.findAllProducers(Unknown Source) 
                                                       at com.hwangjr.rxbus.Bus.register(Unknown Source) 
                                                       at cn.youcaitv.live.e.a.a.onCreate(Unknown Source) 
                                                       at cn.youcaitv.live.usercenter.PreLoginActivity.onCreate(Unknown Source) 
                                                       at android.app.Activity.performCreate(Activity.java:6100) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1109) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2401) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
                                                       at android.app.ActivityThread.access$1200(ActivityThread.java:163) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5595) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by hwangjr** [comment]
我看错误日志，是在cn.youcaitv.live.usercenter.PreLoginActivity类，你注解了Produce，在解析Produce注解时候发生错误，确认下此方法处理了什么。

**Comment by hwangjr** [comment]
@huweigoodboy @kebbs ，还有此问题吗？若没有将关闭此issue。

**Comment by huweigoodboy** [comment]
@hwangjr 没有问题了 谢谢 是我没有keep rxbus和rxandroid

**Comment by hwangjr** [comment]
OK

**Comment by kebbs** [comment]
ok thanks
