### ISSUE TITLE
release版本出现的错误

### ISSUE THREAD

**Issue by jinweime** [AndroidKnife/RxBus#98]
Caused by: java.lang.NoSuchFieldException: No field producerIndex in class Lf/d/e/b/j; (declaration of 'f.d.e.b.j' appears in /data/app/com.seenjoy.yxqn-IEY5mvOthUvIZmzMmF5kLg==/base.apk)
        at java.lang.Class.getDeclaredField(Native Method)
        at f.d.e.b.q.a(Unknown Source:0)
        at f.d.e.b.j.<clinit>(Unknown Source:4) 
        at f.d.a.g$a.<init>(Unknown Source:41) 
        at f.d.a.g.a(Unknown Source:21) 
        at f.d.a.g.call(Unknown Source:2) 
        at f.d.a.d.a(Unknown Source:6) 
        at f.d.a.d.call(Unknown Source:2) 
        at f.f.a(Unknown Source:41) 
        at f.f.b(Unknown Source:0) 
        at f.f.a(Unknown Source:21) 
        at com.hwangjr.rxbus.entity.SubscriberEvent.initObservable(Unknown Source:27) 
        at com.hwangjr.rxbus.entity.SubscriberEvent.<init>(Unknown Source:45) 
        at com.hwangjr.rxbus.finder.AnnotatedFinder.findAllSubscribers(Unknown Source:90) 
        at com.hwangjr.rxbus.finder.Finder$1.findAllSubscribers(Unknown Source:0) 
        at com.hwangjr.rxbus.Bus.register(Unknown Source:162) 
        at com.seenjoy.yxqn.ui.map.MapJobActivity.onCreate(Unknown Source:7) 
        at android.app.Activity.performCreate(Activity.java:7343) 
        at android.app.Activity.performCreate(Activity.java:7333) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7555) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963) 
    #++++++++++++++++++++++++++++++++++++++++++#

这是我的混淆配置文件，报错的文件是MapJobActivity.kt
-dontwarn com.hwangjr.rxbus.**
-keep class com.hwangjr.rxbus.** { *; }
-keep class com.hwangjr.rxbus.finder.** { *; }
-keep class com.hwangjr.rxbus.thread.EventThread { *; }
-keepattributes *Annotation
-keepclassmembers class ** {
    @com.hwangjr.rxbus.annotation.Subscribe public *;
    @com.hwangjr.rxbus.annotation.Produce public *;
    public void onEvent(**);
    public void onEventMainThread(**);
}
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    !static !transient <fields>;
    !private <fields>;
    !private <methods>;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

**Comment by hwangjr** [comment]
确认下 `producerIndex` 这个字段是否真实存在。
